// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from generate.go.

// Package aliaspkg contains generated code by adptool.
package aliaspkg

import (
	pkg1 "github.com/origadmin/adptool/testdata/duplicate/pkg1"
	pkg2 "github.com/origadmin/adptool/testdata/duplicate/pkg2"
	pkg3 "github.com/origadmin/adptool/testdata/duplicate/pkg3"
	sourcepkg1 "github.com/origadmin/adptool/testdata/duplicate/sourcepkg"
	sourcepkg21 "github.com/origadmin/adptool/testdata/duplicate/sourcepkg2"
	sourcepkg3 "github.com/origadmin/adptool/testdata/duplicate/sourcepkg3"
	sourcePkg4 "github.com/origadmin/adptool/testdata/source-pkg4"
	sourcepkg "github.com/origadmin/adptool/testdata/sourcepkg"
	sourcepkg2 "github.com/origadmin/adptool/testdata/sourcepkg2"
	custompkg "github.com/origadmin/adptool/testdata/sourcepkg3"
)

const (
	ExportedConstant = sourcepkg.ExportedConstant
	MaxRetries       = sourcepkg.MaxRetries
	DefaultTimeout   = sourcepkg2.DefaultTimeout
	MaxRetries1      = sourcepkg2.MaxRetries
	Version          = sourcepkg2.Version
	DefaultTimeout1  = custompkg.DefaultTimeout
	MaxRetries2      = custompkg.MaxRetries
	PriorityHigh     = custompkg.PriorityHigh
	PriorityLow      = custompkg.PriorityLow
	PriorityMedium   = custompkg.PriorityMedium
	StatusFailed     = custompkg.StatusFailed
	StatusPending    = custompkg.StatusPending
	StatusRunning    = custompkg.StatusRunning
	StatusSuccess    = custompkg.StatusSuccess
	StatusUnknown    = custompkg.StatusUnknown
	Version1         = custompkg.Version
)

var (
	ConfigValue      = sourcepkg.ConfigValue
	ExportedVariable = sourcepkg.ExportedVariable
	ConfigValue1     = sourcepkg2.ConfigValue
	DefaultWorker    = sourcepkg2.DefaultWorker
	StatsCounter     = sourcepkg2.StatsCounter
	ConfigValue2     = custompkg.ConfigValue
	DefaultWorker1   = custompkg.DefaultWorker
	Processors       = custompkg.Processors
	StatsCounter1    = custompkg.StatsCounter
)

type (
	Product1                                      = pkg1.Product
	ProductService1                               = pkg1.ProductService
	User1                                         = pkg1.User
	UserService1                                  = pkg1.UserService
	User2                                         = pkg2.User
	UserService2                                  = pkg2.UserService
	Product2                                      = pkg3.Product
	ProductService2                               = pkg3.ProductService
	Product3                                      = sourcepkg1.Product
	ProductService3                               = sourcepkg1.ProductService
	User3                                         = sourcepkg1.User
	UserService3                                  = sourcepkg1.UserService
	User4                                         = sourcepkg21.User
	UserService4                                  = sourcepkg21.UserService
	CommonService1                                = sourcepkg3.CommonService
	Product4                                      = sourcepkg3.Product
	User5                                         = sourcepkg3.User
	Data1                                         = sourcePkg4.Data
	GenericHandler1[T any]                        = sourcePkg4.GenericHandler[T]
	Handler1                                      = sourcePkg4.Handler
	Model1                                        = sourcePkg4.Model
	Service1                                      = sourcePkg4.Service
	CommonStruct1                                 = sourcepkg.CommonStruct
	ExportedInterface1                            = sourcepkg.ExportedInterface
	ExportedType1                                 = sourcepkg.ExportedType
	MyStruct1                                     = sourcepkg.MyStruct
	CommonStruct2                                 = sourcepkg2.CommonStruct
	ComplexInterface1                             = sourcepkg2.ComplexInterface
	InputData1                                    = sourcepkg2.InputData
	OutputData1                                   = sourcepkg2.OutputData
	Worker1                                       = sourcepkg2.Worker
	CommonStruct3                                 = custompkg.CommonStruct
	ComplexGenericInterface1[T any, K comparable] = custompkg.ComplexGenericInterface[T, K]
	EmbeddedInterface1                            = custompkg.EmbeddedInterface
	GenericWorker1[T any]                         = custompkg.GenericWorker[T]
	HandlerFunc1[T any]                           = custompkg.HandlerFunc[T]
	InputData2[T any]                             = custompkg.InputData[T]
	IntAlias1                                     = custompkg.IntAlias
	OutputData2                                   = custompkg.OutputData
	Priority1                                     = custompkg.Priority
	ProcessConfig1                                = custompkg.ProcessConfig
	ProcessFunc1                                  = custompkg.ProcessFunc
	ProcessOption1                                = custompkg.ProcessOption
	Status1                                       = custompkg.Status
	StatusAlias1                                  = custompkg.StatusAlias
	TimeAlias1                                    = custompkg.TimeAlias
	Worker2                                       = custompkg.Worker
	WorkerConfig1                                 = custompkg.WorkerConfig
	WorkerOption1                                 = custompkg.WorkerOption
)

func CommonFunction() string {
	return sourcepkg.CommonFunction()
}

func ExportedFunction() {
	sourcepkg.ExportedFunction()
}

func CommonFunction1() string {
	return sourcepkg2.CommonFunction()
}

func NewWorker(name string) *sourcepkg2.Worker {
	return sourcepkg2.NewWorker(name)
}

func CommonFunction2() string {
	return custompkg.CommonFunction()
}

func Filter[T any](ts []T, fn func(T) bool) []T {
	return custompkg.Filter[T](ts, fn)
}

func Map[T, U any](ts []T, fn func(T) U) []U {
	return custompkg.Map[T, U](ts, fn)
}

func NewGenericWorker[T any](name string, data T, processor func(T) error) *custompkg.GenericWorker[T] {
	return custompkg.NewGenericWorker[T](name, data, processor)
}

func NewWorker1(name string, options ...custompkg.WorkerOption) *custompkg.Worker {
	return custompkg.NewWorker(name, options...)
}
