// Code generated by adptool. DO NOT EDIT.
// source: loader.go

package engine

import (
	 ""
	"bufio"
	"context"
	"fmt"
	"go/ast"
	"go/token"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"github.com/origadmin/adptool/internal/config"
	"github.com/origadmin/adptool/internal/loader"
	adpparser "github.com/origadmin/adptool/internal/parser"
)

// Loader is an adapter for .Loader
type Loader = .Loader

// Parser is an adapter for .Parser
type Parser = .Parser

// NewLoader is an adapter for .NewLoader
func NewLoader(fsys fs.FS, parser Parser, cfg *config.Config, logger *slog.Logger) (*Loader) {
	return .NewLoader(fsys, parser, cfg, logger)
}// Load is an adapter method for .Load
func (l *Loader) Load(ctx context.Context, paths []string) (*LoadContext, error) {
	return l.Load(ctx, paths)
}// LoadConfig is an adapter method for .LoadConfig
func (l *Loader) LoadConfig(path string) (*config.Config, error) {
	return l.LoadConfig(path)
}// FileSystemParser is an adapter for .FileSystemParser
type FileSystemParser = .FileSystemParser

// NewFileSystemParser is an adapter for .NewFileSystemParser
func NewFileSystemParser() (*FileSystemParser) {
	return .NewFileSystemParser()
}// ParseFile is an adapter method for .ParseFile
func (p *FileSystemParser) ParseFile(filePath string) (*ast.File, *token.FileSet, error) {
	return p.ParseFile(filePath)
}