// Code generated by adptool. DO NOT EDIT.
// source: loader_test.go

package engine

import (
	 ""
	"context"
	"go/ast"
	"go/token"
	"io"
	"log/slog"
	"strings"
	"testing"
	"testing/fstest"
	"github.com/origadmin/adptool/internal/config"
)

// ParseFile is an adapter method for .ParseFile
func (m *mockParser) ParseFile(filePath string) (*ast.File, *token.FileSet, error) {
	return m.ParseFile(filePath)
}// TestLoader_New is an adapter for .TestLoader_New
func TestLoader_New(t *testing.T) {
	return .TestLoader_New(t)
}// TestLoader_Load is an adapter for .TestLoader_Load
func TestLoader_Load(t *testing.T) {
	return .TestLoader_Load(t)
}// TestLoader_LoadConfig is an adapter for .TestLoader_LoadConfig
func TestLoader_LoadConfig(t *testing.T) {
	return .TestLoader_LoadConfig(t)
}